services:
  - type: web
    name: helpbellorder
    runtime: docker
    plan: starter
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: ZAMMAD_WEB_CONCURRENCY
        value: 0
      - key: ZAMMAD_READY_FILE_PATH
        value: /tmp/zammad.ready
      - key: DATABASE_URL
        fromDatabase:
          name: helpbellorder-db
          property: connectionString
      - key: REDIS_URL
        fromDatabase:
          name: helpbellorder-redis
          property: connectionString

databases:
  - name: helpbellorder-db
    plan: starter
    databaseName: helpbellorder
    user: helpbellorder

  - name: helpbellorder-redis
    plan: starter
